### ISSUE TITLE
Melomel can't find element

### ISSUE THREAD

**Issue by laran** [benbjohnson/melomel.rb#13]
I'm running Melomel from Cucumber.

I've tried the Melomel::Cucumber.find_by_xxxx!() methods, but none of them seem to find the element (an instance of a subclass of Button).

What are the limits to finding elements. Any tips you'd recommend? I haven't found anything in the examples or documentation.

Thanks

**Comment by benbjohnson** [comment]
Can you paste the Ruby code that you're trying to run? It should find pretty much anything in the display list (except for some elements under rawChildren).

**Comment by laran** [comment]
I've tried all of the following:

button = Melomel::Cucumber.find_by_label!('PermissionButton', 'Add')
button = Melomel::Cucumber.find_by_label!('com.foo.PermissionButton', 'Add')
button = Melomel::Cucumber.find_by_id!('PermissionButton', 'add')

**Comment by laran** [comment]
Do I need to do any waiting for elements to load?

Here's my scenario:

```
Scenario: Create a project
    Given I login as "admin" with password "password"
    When I click the "Projects" tab
    And I click the "Add" button
```

I haven't gotten past that yet. But, when I click the Projects tab there's some dynamic loading of the viewStack that contains the button I try to click. Do I have to wait for the viewStack to load before the add button will be available? If so, do I just wrap the click on the add button with Melomel::Cucumber.run! { /\* click button here */ }

**Comment by benbjohnson** [comment]
You may need to wrap it in run!. That will cause Melomel to wait for 5 frames (or wait for any busy cursor to be removed) before continuing on to the action.

**Comment by laran** [comment]
I think it might have to do with dynamic module loading. When I click the tab, a module then loads. The button I want to click is inside that module. So perhaps the button isn't found because it isn't loaded yet.

Is there a way to wait for a module to load?

**Comment by benbjohnson** [comment]
You could have a loop that searches for the module in the display hierarchy. But the easiest method is to just add a `sleep` call:

``` ruby
# Sleep for three seconds
sleep 3
```

**Comment by laran** [comment]
That did it! Waiting for the module to load, then proceeding did it. Thanks so much! Great library you've got here. Docs could be better, but it's a much needed tool Thanks!

**Comment by benbjohnson** [comment]
Awesome! I'm glad it worked. The docs are mirrored from the Melomel GitHub wiki so if you feel like making the documentation better, you can change it here:

https://github.com/benbjohnson/melomel/wiki

Let me know if you make changes and I'll push them to the http://melomel.info web site.
