### ISSUE TITLE
Melomel::Cucumber.get_grid_data(grid) with cursor instead of dataProvider

### ISSUE THREAD

**Issue by scho** [benbjohnson/melomel.rb#15]
Hi,
I tried to validate the data in a data grid and it seems, that it only works if your dataProvider is some ArrayCollection. But it does not work, if you use a HierarchicalCollectionView, which has as a source an ArrayCollection. (I assume, that having a GroupingCollection is the same)

But if you get your data with a cursor, it works:

``` ruby
cursor = grid.dataProvider.createCursor()
while !cursor.afterLast do
  grid_data << cursor.current
  break if !cursor.moveNext()
end
```

I added these modifications to `self.get_grid_data(grid)` in `Melomel::Cucumber`.

So, what do you think about it? Is this the right way to do it? If you want to, I can commit it to my fork and send you a pull request.

I would also like the `self.get_grid_data(grid)` method to ignore columns, that are not visible.

**Comment by benbjohnson** [comment]
That looks correct. The underlying dataProvider in DataGrid is always an ICollectionView so that should work for any type of data. Go ahead and send me a pull request and I'll push out a new version.

**Comment by laran** [comment]
I'll keep an eye out for that push. I want to try it too.

**Comment by scho** [comment]
In order to test my new code, I tried to run `rake test`, which worked. But running the features with cucumber (`bundle exec cucumber features`) did not work for me. I needed to include RSpec into melomel.gemspec. But I assume, this can't be the right way to go. So how do you run your features?

**Comment by benbjohnson** [comment]
That's a good question. I usually just run `rake test` or `cucumber` and it loads RSpec somehow on my machine. You can add RSpec to the list of development dependencies in the gemspec:

```
s.add_development_dependency('rspec', '~> 2.6.0')
```

**Comment by laran** [comment]
Is this a Flex 4 specific thing? There's no createCursor method method in Flex 3 right?

**Comment by benbjohnson** [comment]
`mx.collections.ListCollectionView#createCursor()` has been available since Flex 3. Also, if it didn't exist, it should throw an error.

Is the element or data that you're trying to access in the `AdvancedDataGrid` visible when you try to find it using Melomel? The ADG reuses the renderers so it might not be available if it's not onscreen.
