### ISSUE TITLE
How would I click on an element in an AdvancedDataGrid?

### ISSUE THREAD

**Issue by laran** [benbjohnson/melomel.rb#17]
I see here how the selectedIndex is used to select elements in a data grid.
https://github.com/benbjohnson/melomel.rb/blob/master/lib/melomel/cucumber/data_grid_steps.rb

But I have a button which activates on the click action of a row. Setting the selectedIndex doesn't seem to trigger the activation of the button.

How would I actually click on the grid element?

**Comment by benbjohnson** [comment]
If you have a reference to the row then you can do:

``` ruby
Melomel::UI.click(row)
```

That imitates a mouseDown -> mouseUp -> click event sequence.

**Comment by laran** [comment]
Here's what I'm doing:
Melomel.click Melomel::Cucumber.find_grid_element_by_label(grid, name)

And here's what happens:
Error #1034: Type Coercion failed: cannot convert com.foo::MyVO@468a709 to flash.display.InteractiveObject. (Melo
mel::Error)

The element that's returned isn't the row itself, it's the data element that the row renders. I think this is happening because the getGridSelectedItem() function has been overwritten in a parent class to my grid.

What I want is a method to "click row x of grid y".

**Comment by laran** [comment]
I also tried this:

  index = Melomel::Cucumber.find_grid_index_by_label(grid, name)
  renderer = grid.indexToItemRenderer(index)
  Melomel.click renderer

Which resulted in this:

Mouse events are not enabled on component (Melomel::Error)

**Comment by benbjohnson** [comment]
The "Mouse events are not enabled" error is occurring because your renderer has `mouseEnabled` set to `false`. What type of object is being returned into `renderer`?

**Comment by laran** [comment]
I'm not sure what type of object is returned. It's wrapped by ObjectProxy.
How can I inspect the inner object?

**Comment by benbjohnson** [comment]
You can find the inner object of an object proxy by using the `object` property of the proxy.

**Comment by laran** [comment]
renderer = grid.indexToItemRenderer(index)
puts "#{renderer.object.class}"

prints NilClass

**Comment by laran** [comment]
So I just read the Flex docs for onChange. According to the docs it triggers "when selectedIndex or selectedItem change as the result of user interaction".

So, I can set the selectedIndex. But I haven't figured out a way to "simulate user interaction" to trigger onChange.

Can Melomel do this?

**Comment by benbjohnson** [comment]
Unfortunately, it doesn't allow it right now. Melomel can only instantiate objects that have constructors with no required arguments and `flash.events.Event` requires the `type` argument. It is something that should be added to Melomel. In the meantime, you can add a helper class to your code and do the following:

``` as3
package com.mydomain.utils
{
import flash.events.Event;
import flash.events.EventDispatcher;

public class MyHelperUtil
{
  static public function dispatchChangeEvent(component:EventDispatcher):void
  {
    component.dispatchEvent(new Event(Event.CHANGE));
  }
}
}
```

Then you'll need to add a reference to your class somewhere in your AS3 code and then do the following in Ruby:

``` ruby
helper = Melomel.get_class!('com.mydomain.utils.MyHelperUtil')
helper.dispatchChangeEvent(row)
```

**Comment by laran** [comment]
I'll look into that one.

I'll probably run into the same situation with Trees right? I don't see any helpers to select Tree elements. So I'll have to do it manually using selectedIndex/selectedItem, right?

**Comment by benbjohnson** [comment]
Yeah, you'll need to do that for trees too. If you end up writing any helpers, submit them as a patch and I'll merge them into Melomel.

**Comment by laran** [comment]
So I tried this. But I get the following error:

"Cannot find class: com.my.EventUtil"

My class is this:

import flash.events.Event;
import flash.events.EventDispatcher;

import mx.events.ListEvent;

public class EventUtil {
    static public function dispatchListChangeEvent(component:EventDispatcher):void
    {
      component.dispatchEvent(new Event(ListEvent.CHANGE));
    }
}
}

# Ruby

def dispatch_list_change_event(component)
  helper = Melomel.get_class!("com.my.EventUtil")
  helper.dispatchListChangeEvent(component)
end

And I've verified that the class is available by calling it inside AS code from somewhere else.

So, is Melomel able to get references to statics?

**Comment by benbjohnson** [comment]
It can call static methods. Is your package named "com.my"? Melomel just does a simple `getDefinitionByName()` call to retrieve the class.

What happens when you leave the AS calling code in your code? It could be that you are removing the test call you made in AS and if that was the only reference to the EventUtil class then the compiler will remove the EventUtil class from the SWF. Are you leaving your AS test calling code in there when you run Melomel?

**Comment by laran** [comment]
I worked around the problem by adding a method on my AdvancedDataGrid subclass which invoked the onChange method explicitly. Problem solved.

Regarding trees, I haven't found any code for working with trees. In particular I want to get data out of the tree to select an index similar to the way Melomel::Cucumber.find_index_by_label works. That only works for grids though it seems.

Are there any samples to demonstrate working with trees in Melomel?

**Comment by benbjohnson** [comment]
The `Tree` is a little more complicated. There's not any code for it currently. If you want to implement a helper method call to select an item, you can use the Tree.dataDescriptor to traverse the dataProvider and use the tree's labelField (or labelFunction) on each object in the dataProvider's hierarchy. Once you find the object you want to select, you can expand the tree using Tree.expandItem() and then set the Tree.firstVisibleItem to the object you selected.

The tree can be a little tricky though. You may be able to select the object that you find using the dataDescriptor but not expand and show it. It doesn't look as good but it might be easier and still achieve what you need.

**Comment by laran** [comment]
I can't get tree.dataProvider.each to work for me. How would I iterate over
the elements in the list. I'd like to do it recursively to build out the
tree basically as a 2d array of strings.

**Comment by benbjohnson** [comment]
Take a look at the docs for mx.controls.treeClasses.ITreeDataDescriptor. Here's some pseudocode:

``` as3
public function findTreeItemByLabel(tree:Tree, label:String):Object
{
  return _findTreeItemByLabel(tree, label, tree.dataProvider);
}

public function _findTreeItemByLabel(tree:Tree, label:String, obj:Object):Object
{
  var data:Object = tree.dataDescriptor.getData(obj);

  // Check if this item has the correct label
  if(data[tree.labelField] == label || (tree.labelFunction != null && tree.labelFunction(data) == label)) {
    return obj;
  }
  // Otherwise search children
  else {
    var children:ICollectionView = tree.dataDescriptor.getChildren(obj);
    for each(var child:Object in children) {
      var ret:Object = _findTreeItemByLabel(tree, label, child);
      if(ret) {
        return ret;
      }
    }
  }

  // If nothing found, return null
  return null;
}
```

I didn't test that but hopefully it makes sense. You might need to make changes with the data/obj relationship but that's the general idea.

Let me know if you have any questions.

**Comment by laran** [comment]
So I'll have to put this in the flex code? Or can it go in the ruby code?

**Comment by benbjohnson** [comment]
Put it in the AS code. If you get something working, let me know and I'll integrate it into the Melomel SWC.
