### ISSUE TITLE
Quieting melomel when classes can't be found

### ISSUE THREAD

**Issue by laran** [benbjohnson/melomel.rb#19]
I get this printed out to stdout every time melomel can't find a class. Is there a way to turn it off?

Error: Classes could not be found
        at melomel.core::UI$/findAll()
        at melomel.core::UI$/find()
        at Function/http://adobe.com/AS3/2006/builtin::apply()
        at melomel.commands::InvokeMethodCommand/execute()
        at melomel.core::Bridge/receive()
        at melomel.core::Bridge/socket_onData()
        at flash.events::EventDispatcher/dispatchEventFunction()
        at flash.events::EventDispatcher/dispatchEvent()
        at flash.net::XMLSocket/scanAndSendEvent()

**Comment by benbjohnson** [comment]
What classes is it trying to find? There's not a built-in way right now. What's the use case where you are looking for classes you can't find? You could wrap your Ruby code in a `begin/rescue/end` block and just ignore the rescue.

**Comment by laran** [comment]
I just found it on line 153 of messaging.rb. Maybe making this configurable would be a good idea. I'd like it.

**Comment by laran** [comment]
I have a rather complicated flex app that loads modules at various times. I have a number of situations where I want to click a button, then wait for a module to load, then click an item inside the loaded module. To do this right now I just loop and sleep until I can find the module class. At that point I know that it's loaded. It's annoying to have the stderr spam. it's expected that the class won't be found, which I verify by find returning nil.

**Comment by benbjohnson** [comment]
I don't want to ignore the errors because they're typically good to see. If you want to check for the existence of a class, try doing something like this:

``` ruby
typeClass = Melomel.get_class('melomel.core.Type')
class_ref = typeClass.getClass('com.domain.MyClass')

if !class_ref.nil?
  # Do something if class exists.
else
  # Do something if class doesn't exist.
end
```

The `melomel.core.Type#getClass()` method will retrieve a class reference by name if it exists or return null if it doesn't. That way you won't throw any errors.
